### ISSUE TITLE
Demo Prototype

### ISSUE THREAD

**Issue by hankthewhale** [hankthewhale/monitorhub#5]
# Sprint Goal
 - Create MVP prototype 
 - Demo 

___
###### Functionality
- [ ] #4 Dump Data to file
- [ ] #2 Add Markdown Parser
- [ ] #3 Style Widgets

###### Look and Feel
- [ ] #3 Style Widgets

___
### Milestone Metrics and Targets
This sprint will run for **1 week** and will be considered a success based upon:
- [ ] A demo-able UI for review and critique 
- [ ] Ability to display mostly meaningful data
